In [1]:
import numpy as np
import pandas as pd

In [2]:
df =pd.DataFrame({'Review':['This book book  is excellent for ML','This book is not suitable for beginners.',
                        'Those who learn ML, I will recommend this book.','I was disappointed by this book.'],
              'sentiment':[1,0,1,0]
             
             })

In [3]:
df

Review  sentiment
0              This book book  is excellent for ML          1
1         This book is not suitable for beginners.          0
2  Those who learn ML, I will recommend this book.          1
3                 I was disappointed by this book.          0

## Parameters:
	1. Lowercase
	2. Stop_words
	3. Max_df -   
	4. Min_df
	5. Max_features
	6. Binary
    7. N-gram
    
## Methods:
	7. Vocabulary_
	8. get_feather_out 

# CountVectorizer

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1,2))
bag_of_words = cv.fit_transform(df['Review'])

In [5]:
bag_of_words.toarray()# 4,17+19

array([[0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0]], dtype=int64)

In [6]:
cv.vocabulary_

{'this': 26,
 'book': 1,
 'is': 13,
 'excellent': 8,
 'for': 10,
 'ml': 18,
 'this book': 27,
 'book book': 2,
 'book is': 3,
 'is excellent': 14,
 'excellent for': 9,
 'for ml': 12,
 'not': 20,
 'suitable': 24,
 'beginners': 0,
 'is not': 15,
 'not suitable': 21,
 'suitable for': 25,
 'for beginners': 11,
 'those': 28,
 'who': 32,
 'learn': 16,
 'will': 34,
 'recommend': 22,
 'those who': 29,
 'who learn': 33,
 'learn ml': 17,
 'ml will': 19,
 'will recommend': 35,
 'recommend this': 23,
 'was': 30,
 'disappointed': 6,
 'by': 4,
 'was disappointed': 31,
 'disappointed by': 7,
 'by this': 5}

In [7]:
cv.get_feature_names_out(input_features=None)


array(['beginners', 'book', 'book book', 'book is', 'by', 'by this',
       'disappointed', 'disappointed by', 'excellent', 'excellent for',
       'for', 'for beginners', 'for ml', 'is', 'is excellent', 'is not',
       'learn', 'learn ml', 'ml', 'ml will', 'not', 'not suitable',
       'recommend', 'recommend this', 'suitable', 'suitable for', 'this',
       'this book', 'those', 'those who', 'was', 'was disappointed',
       'who', 'who learn', 'will', 'will recommend'], dtype=object)

# TfidfVectorizer

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf =TfidfVectorizer()
tf_idf = tf.fit_transform(df['Review'])

In [10]:
tf_idf.toarray()

array([[0.        , 0.50767386, 0.        , 0.        , 0.48642536,
        0.38350334, 0.38350334, 0.        , 0.38350334, 0.        ,
        0.        , 0.        , 0.25383693, 0.        , 0.        ,
        0.        , 0.        ],
       [0.45701556, 0.23848968, 0.        , 0.        , 0.        ,
        0.36031631, 0.36031631, 0.        , 0.        , 0.45701556,
        0.        , 0.45701556, 0.23848968, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.21014969, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4027079 , 0.31749953, 0.        ,
        0.4027079 , 0.        , 0.21014969, 0.4027079 , 0.        ,
        0.4027079 , 0.4027079 ],
       [0.        , 0.27717414, 0.53114624, 0.53114624, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.27717414, 0.        , 0.53114624,
        0.        , 0.        ]])

In [17]:
tf.idf_

array([1.91629073, 1.        , 1.91629073, 1.91629073, 1.91629073,
       1.51082562, 1.51082562, 1.91629073, 1.51082562, 1.91629073,
       1.91629073, 1.91629073, 1.        , 1.91629073, 1.91629073,
       1.91629073, 1.91629073])

In [16]:
tf.get_feature_names_out()

array(['beginners', 'book', 'by', 'disappointed', 'excellent', 'for',
       'is', 'learn', 'ml', 'not', 'recommend', 'suitable', 'this',
       'those', 'was', 'who', 'will'], dtype=object)